# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('socialId', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
